language: node_js
install: "npm install; npm install docpad; cd ./node_modules/docpad; npm install; cd ../.."
before_script: "./node_modules/.bin/cake compile"
script: "npm test"
node_js:
  - "0.10"
notifications:
  email:
    recipients:
      - chris@strobedigital.com